CREATE TABLE FABRICANTES (
    NOMBRE_FABRICANTE VARCHAR(30) NOT NULL,
    PAIS VARCHAR(15),
    CONSTRAINT CK_NFAB CHECK (NOMBRE_FABRICANTE = INITCAP(NOMBRE_FABRICANTE)),
    CONSTRAINT PK_FAB PRIMARY KEY (NOMBRE_FABRICANTE)
);

CREATE TABLE MANUFACTURA (
    MARCA VARCHAR(20) NOT NULL,
    NOMBRE_FABRICANTE VARCHAR(30),
    CARTON NUMERIC(2,0) DEFAULT 10,
    EMBALAJE NUMERIC(2,0) DEFAULT 20,
    CONSTRAINT CK_CARTON CHECK (CARTON > 0),
    CONSTRAINT CK_EMBALAJE CHECK (EMBALAJE > 0),
    CONSTRAINT PK_MAN PRIMARY KEY (MARCA),
    CONSTRAINT FK_MAN_FAB FOREIGN KEY (NOMBRE_FABRICANTE) REFERENCES FABRICANTES (NOMBRE_FABRICANTE) ON DELETE CASCADE
);

CREATE TABLE CIGARRILLOS (
    MARCA VARCHAR(20) NOT NULL,
    FILTRO CHAR(1) NOT NULL,
    COLOR CHAR(1) NOT NULL,
    CLASE VARCHAR(10) NOT NULL,
    MENTOL CHAR(1) NOT NULL,
    NICOTINA NUMERIC(2,1),
    ALQUITRAN NUMERIC(4,2),
    PRECIO_VENTA NUMERIC(3,0),
    PRECIO_COSTO NUMERIC(3,0),
    CONSTRAINT CK_FILTRO CHECK (FILTRO IN ('S', 'N')),
    CONSTRAINT CK_COLOR CHECK (COLOR IN ('R', 'N')),
    CONSTRAINT CK_CLASE CHECK (CLASE IN ('Light', 'SuperLight', 'UltraLight', 'Normal')),
    CONSTRAINT CK_MENTOL CHECK (MENTOL IN ('S', 'N')),
    CONSTRAINT CK_PV CHECK (PRECIO_VENTA > 0),
    CONSTRAINT CK_PC CHECK (PRECIO_COSTO > 0),
    CONSTRAINT PK_CIG PRIMARY KEY (MARCA, FILTRO, COLOR, CLASE, MENTOL),
    CONSTRAINT FK_CIG_MAN FOREIGN KEY (MARCA) REFERENCES MANUFACTURA (MARCA) ON DELETE CASCADE
);

CREATE TABLE ESTANCOS (
    NIF_ESTANCO VARCHAR(12) NOT NULL,
    EXPENDEDURIA NUMERIC(4,0) NOT NULL,
    CP_ESTANCO NUMERIC(5,0) NOT NULL,
    NOMBRE_ESTANCO VARCHAR(30) NOT NULL,
    DIRECCION_EGTANCO VARCHAR(30),
    LOCALIDAD_ESTANCO VARCHAR(15),
    PROVINCIA_ESTANCO VARCHAR(15),
    CONSTRAINT CK_NEST CHECK (NOMBRE_ESTANCO = INITCAP(NOMBRE_ESTANCO)),
    CONSTRAINT CK_NIF CHECK (NIF_ESTANCO = UPPER(NIF_ESTANCO)),
    CONSTRAINT PK_EST PRIMARY KEY (NIF_ESTANCO),
    CONSTRAINT SK_EST UNIQUE (EXPENDEDURIA, CP_ESTANCO)
);

CREATE TABLE ALMACENES (
    NIF_ESTANCO VARCHAR(12) NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    FILTRO CHAR(1) NOT NULL,
    COLOR CHAR(1) NOT NULL,
    CLASE VARCHAR(10) NOT NULL,
    MENTOL CHAR(1) NOT NULL,
    UNIDADES NUMERIC(4,0),
    CONSTRAINT CK_UNI CHECK (UNIDADES >= 0),
    CONSTRAINT PK_ALM PRIMARY KEY (NIF_ESTANCO, MARCA, FILTRO, COLOR, CLASE, MENTOL),
    CONSTRAINT FK_ALM_CIG FOREIGN KEY (MARCA, FILTRO, COLOR, CLASE, MENTOL) REFERENCES CIGARRILLOS (MARCA, FILTRO, COLOR, CLASE, MENTOL) ON DELETE CASCADE,
    CONSTRAINT FK_ALM_EST FOREIGN KEY (NIF_ESTANCO) REFERENCES ESTANCOS (NIF_ESTANCO) ON DELETE CASCADE
);

CREATE TABLE COMPRAS (
    NIF_ESTANCO VARCHAR(12) NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    FILTRO CHAR(1) NOT NULL,
    COLOR CHAR(1) NOT NULL,
    CLASE VARCHAR(10) NOT NULL,
    MENTOL CHAR(1) NOT NULL,
    FECHA_COMPRA DATE NOT NULL,
    C_COMPRADA NUMERIC(3,0),
    PRECIO_COMPRA NUMERIC(6,0),
    CONSTRAINT CK_C_COMPRADA CHECK (C_COMPRADA > 0),
    CONSTRAINT CK_PRECIO_COMPRA CHECK (PRECIO_COMPRA > 0),
    CONSTRAINT PK_COM PRIMARY KEY (NIF_ESTANCO, MARCA, FILTRO, COLOR, CLASE, MENTOL, FECHA_COMPRA),
    CONSTRAINT FK_COM_ALM FOREIGN KEY (NIF_ESTANCO, MARCA, FILTRO, COLOR, CLASE, MENTOL) REFERENCES ALMACENES (NIF_ESTANCO, MARCA, FILTRO, COLOR, CLASE, MENTOL) ON DELETE CASCADE
);

CREATE TABLE VENTAS (
    NIF_ESTANCO VARCHAR(12) NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    FILTRO CHAR(1) NOT NULL,
    COLOR CHAR(1) NOT NULL,
    CLASE VARCHAR(10) NOT NULL,
    MENTOL CHAR(1) NOT NULL,
    FECHA_VENTA DATE NOT NULL,
    C_VENDIDA NUMERIC(3,0),
    PRECIO_VENTA NUMERIC(6,0),
    CONSTRAINT CK_C_VENDIDA CHECK (C_VENDIDA > 0),
    CONSTRAINT CK_PRECIO_VENTA CHECK (PRECIO_VENTA > 0),
    CONSTRAINT PK_VEN PRIMARY KEY (NIF_ESTANCO, MARCA, FILTRO, COLOR, CLASE, MENTOL, FECHA_VENTA),
    CONSTRAINT FK_VEN_ALM FOREIGN KEY (NIF_ESTANCO, MARCA, FILTRO, COLOR, CLASE, MENTOL) REFERENCES ALMACENES (NIF_ESTANCO, MARCA, FILTRO, COLOR, CLASE, MENTOL) ON DELETE CASCADE
);
